version: '3'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: development
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    env_file:
      - docker-compose.dev.env
    tty: true
    stdin_open: true
    restart: on-failure

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    environment:
      POSTGRES_USER: tvs
    restart: on-failure

  elasticsearch:
    image: elasticsearch
    depends_on:
      - db
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  pg_data: {}
  elasticsearch: {}
